- name: Install Docker
  dnf:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Clone application repo
  git:
    repo: 'https://github.com/Lakshmanp145/docker-compose.git'
    dest: /opt/3tier-app
    version: main

- name: Copy environment file securely
  copy:
    src: .env
    dest: /opt/3tier-app/.env
    mode: '0600'

- name: Start application with Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/3tier-app
